export const HeadingTitle = {
  dashboard: 'Dashboard',
  published: 'Published Templates',
  drafts: 'Manage Saved Drafts',
  themes: 'Themes',
  library: 'Template Library',
  vision: 'Vision & Mission',
  agencies: 'Agencies & Departments',
  people: 'Principal Officers',
  responsibility: 'Responsibilities',
  newsroom: 'Newsroom',
  events: 'Events',
  gallery: 'Gallery',
  resources: 'Resources',
  contact: 'Contact Information',
  services: 'Services',
  forms: 'Form Builder',
  messages: 'Messages',
  subscribers: 'Subscribers',
  settings: 'Settings',
};
